name: SpigotTools
version: '${project.version}'
main: me.rfmineguy.spigot_hammers.SpigotTools
api-version: 1.18
description: A plugin implementing a mechanic similar to TConstruct's hammers and excavators
commands:
  hammer:
    description: Gives the player a hammer
    usage: /hammer <type>
  excavator:
    description: Gives the player an excavator
    usage: /excavator <type>
  st-effect:
    description: Options for the effect added by SpigotTools
depend: []