name: SpigotTools
version: '${project.version}'
main: me.rfmineguy.spigot_hammers.SpigotTools
api-version: 1.18
description: A plugin implementing new mining mechanics
commands:
  spigot-tools:
    description: Everything spigot tools related is done through here